### ISSUE TITLE
Allow Androids shared preferences name to be set dynamically

### ISSUE THREAD

**Issue by wytlytningNZ** [TheCocoaProject/cordova-plugin-nativestorage#104]
We have existing apps in production that have stored their preferences under a different name than "NativeStorage".

We would like to be able to configure this value from cordova's `config.xml` file.

Related PR is here: https://github.com/TheCocoaProject/cordova-plugin-nativestorage/pull/103

**Comment by wytlytningNZ** [comment]
Thankyou for merging https://github.com/TheCocoaProject/cordova-plugin-nativestorage/pull/103 @GillesC 

Am I able to get a version bump please? 🙏

**Comment by GillesC** [comment]
After some more testing, I will jump up the version number and publish it
to nominate :)

**Comment by wytlytningNZ** [comment]
Thankyou very much

**Comment by alokrajiv** [comment]
Let me close this for you guys! 

Feel free to re-open if needed ofcourse.

**Comment by wytlytningNZ** [comment]
We able to get a release cut for this resolved issue?
PR merged here: https://github.com/TheCocoaProject/cordova-plugin-nativestorage/pull/103
