### ISSUE TITLE
setItem or getItem returns no value (iOS 11)

### ISSUE THREAD

**Issue by josteph** [TheCocoaProject/cordova-plugin-nativestorage#110]
Scenario:

I have a data returned from the server in [object Object] format.
I use `const parsed = JSON.parse(JSON.stringify(data))`, it will become:
```
{
 access_token: '....',
 refresh_token: '....'
}
```

I was able to alert the data like: `alert(data.access_token)` (showing me the string value) before actually storing the string of access_token like `window.NativeStorage.setItem('access_token', parsed.access_token)`

But it seems during getItem, nothing is returned (empty value). It is either setItem or getItem or both. So here's the output log from xCode when actually calling `window.NativeStorage.getItem('access_token')`:
```
Error in Success callbackId: NativeStorage45281472 : TypeError: error is not a function. (In 'error(new NativeStorageError(NativeStorageError.JSON_ERROR, "JS", err))', 'error' is undefined)
2018-02-08 10:04:32.088407+0700 Qourt[4369:2011891] Error in Success callbackId: NativeStorage45281473 : TypeError: error is not a function. (In 'error(new NativeStorageError(NativeStorageError.JSON_ERROR, "JS", err))', 'error' is undefined)
2018-02-08 10:04:32.088495+0700 Qourt[4369:2011891] Error in Success callbackId: NativeStorage45281474 : TypeError: error is not a function. (In 'error(new NativeStorageError(NativeStorageError.JSON_ERROR, "JS", err))', 'error' is undefined)
2018-02-08 10:04:32.088579+0700 Qourt[4369:2011891] Error in Success callbackId: NativeStorage45281475 : TypeError: error is not a function. (In 'error(new NativeStorageError(NativeStorageError.JSON_ERROR, "JS", err))', 'error' is undefined)
2018-02-08 10:04:38.988020+0700
```

Is the problem caused by how I store the key? If so, what would be the recommended way to store them?

**Comment by GillesC** [comment]
Dear josteph
Could you try to install the latest version from Github instead of the npm package?
The installation procedure is explained [here](https://github.com/TheCocoaProject/cordova-plugin-nativestorage#reinstallinginstalling-developer-version).

**Comment by josteph** [comment]
@GillesC Thanks for the response!

Is there any difference, specifically for `setItem` or `getItem` methods?

Anyway, I will try to install from Github and will update you the result tonight.

**Comment by GillesC** [comment]
There is no (there should not be any) difference for these methods. 
Thank you for your feedback!

**Comment by Jckf** [comment]
Hello. We might be experiencing the same issue. My app also uses NativeStorage to store a session token, and tried to load it immediately after device ready. The response from NativeStorage is error code 2, ie. item not found. However running the same code a few seconds later works just fine, so it seems the storage is not ready on device ready.

**Comment by josteph** [comment]
@Jckf Hmm my issue is not exactly the same. I'm using also OAuth2 Library, successfully returned the tokens in JSON format and stored using setItem. But got the `JSON_ERROR` instead when calling getItem on the credentials.

@GillesC The issue still remains, the setItem is using JSON.stringify(data) then JSON.parse(data), not sure if this is causing the issue? I will try to putString instead and will give feedback again.

Thanks.

**Comment by josteph** [comment]
Ok I've confirmed the issue here. The token is so long that it even takes long enough for the getItem success callback is actually called. Other short data seems to work fine though.

What's the recommend way to store 4096 length of string?
