### ISSUE TITLE
setItem is broken in iOS in v2.3.0

### ISSUE THREAD

**Issue by beaulac** [TheCocoaProject/cordova-plugin-nativestorage#112]
Calling `setItem` with any value (object, array, string) in iOS causes error code 3.

e.g. 
```javascript
setItem('AnyKey', 'Any Value').catch(err => {/* err has code "3" (NULL_REFERENCE) */})
```

I believe the condition to check for a null reference [here](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/blob/ed3e0d5775f904671e325988562eb74892476234/src/ios/NativeStorage.m#L214) is backwards.

I've opened a PR (#113) that addresses this issue. With this change, `setItem` works as expected.

**Comment by Snead** [comment]
Having the same issue with no changes on our side since when it was working.

**Comment by ayhanbinici** [comment]
I can verify this bug on iOS 11.2.5. Reverting this plugin back to version 2.3.0.

**Comment by DineshKaushik** [comment]
Yes , with latest version of plugin iOS NativeStorageSetItem is broken every time getting Error:3.
But works fine for Android . Reverting back to @2.2.2 solves the issue.

**Comment by dalezak** [comment]
Any ETA on a fix for this issue?

Even though I explicitly set the version of  `cordova-plugin-nativestorage` to `2.2.2`, upon re-adding the iOS or Android platform, the `package.json` gets incremented back to `^2.3.0`.

**Comment by DineshKaushik** [comment]
@dalezak Downgrading to @.2.2.2 worked for me. Don't remove the platform iOS/Android , just remove the plugin and add again and it will work , use following commands:

cordova plugin rm cordova-plugin-nativestorage
cordova plugin add cordova-plugin-nativestorage@2.2.2

**Comment by dalezak** [comment]
Hmm, I've upgraded to `2.3.1` however still getting an error trying to `setItem` for a `boolean` value.
```
this.nativeStorage.setItem("AcceptedTerms", true).then((data:any) => {
  console.log(JSON.stringify(data));
},
(error:any) => {
  console.error(JSON.stringify(error));
});
```
```
{"code":3,"source":"Native","exception":null,"__zone_symbol__currentTask":{"type":"macroTask","state":"notScheduled","source":"setTimeout","zone":"<root>","cancelFn":null,"runCount":0}}
```

**Comment by dalezak** [comment]
@GillesC I'm kind of roadblocked on this, still running into issues on iOS, any thoughts?

**Comment by Snead** [comment]
@dalezak you should use 2.2.2 for now. (Not the adapter, the plugin)
