### ISSUE TITLE
FAQ link does not work

### ISSUE THREAD

**Issue by BorntraegerMarc** [TheCocoaProject/cordova-plugin-nativestorage#116]
In the section "Oh no my stored data is not cleared after reinstalling my application. How do I resolve this 'issue'?
" in the FAQ: https://github.com/TheCocoaProject/cordova-plugin-nativestorage#faq 

you are referencing a stackoverflow question: https://stackoverflow.com/questions/42538421/ionic-nativestorage-not-clear-when-reinstal-application-release

but the link resolves in a 404

**Comment by GillesC** [comment]
Thank you for the feedback.
It seems that the question on SO has been deleted.
I will update the readme.
But short: 
- on Android: https://stackoverflow.com/questions/41808957/sharedpreferences-not-reset-on-reinstall
