### ISSUE TITLE
Plugin works on browser but not on phone

### ISSUE THREAD

**Issue by TakshPSingh** [TheCocoaProject/cordova-plugin-nativestorage#119]
I am using the Phonegap CLI to serve my project and my plugin version is: 2.3.1

So, I wrote the following code to execute after the device is ready:
```javascript
 NativeStorage.getItem("abcd", function() {
     console.log("success");
     alert("success");
 }, function() {
     console.log("fail");
     alert("failed :)");
 });
```

This works perfectly when I am testing it on my browser. However, when I open this app on my android phone, the NativeStorage code does not work at all.

I used weinre to debug my app:

I got the error: ReferenceError: NativeStorage is not defined

![Image of the error](https://i.stack.imgur.com/HAGOx.jpg)

I also removed the plugin and all the platforms and reinstalled them again; however, I am still getting the same error.

Can you please help me find the issue ?

**Comment by GillesC** [comment]
See if issue #82 resolves your problem.

**Comment by GillesC** [comment]
Closed due to inactivity. Will reopen if necessary.
