### ISSUE TITLE
Android returning Null val

### ISSUE THREAD

**Issue by bigHoss101** [TheCocoaProject/cordova-plugin-nativestorage#122]
Hi,

I'm creating a cross platform app with phonegap 6.5.2, it's working fine on IOS. But when I create an android project, it's saving or returning a null value. Is there anything else I need to do to initialise it on android? I'm using the setitem and getstring methods. Is this issue familliar to anyone?

Best Regards,
Hoss

**Comment by GillesC** [comment]
Dear @bigHoss101 
Use `getItem` if you have stored your item using `getItem`.
The `getString` method is deprecated. For more info on the usage see:https://github.com/TheCocoaProject/cordova-plugin-nativestorage#usage.

This should resolve you problem.

**Comment by GillesC** [comment]
I will close this issue. If this, however, does not solve your problem be free to reopen it.
