### ISSUE TITLE
Ionic 4 Beta Error

### ISSUE THREAD

**Issue by mmt78** [TheCocoaProject/cordova-plugin-nativestorage#125]
I am trying to use this plugin on Ionic 4 project. But I am getting 'TypeError: Object(...) is not a function' error. Please help me solve this problem.

**Comment by ThorvaldAagaard** [comment]
This error is because you haven't updated your references to the new version of Ionic Native

**Comment by GillesC** [comment]
Please reopen if the aforementioned comment did not resolve your issue.
