### ISSUE TITLE
Native Storage issue in IOS devices

### ISSUE THREAD

**Issue by sachinsemlety** [TheCocoaProject/cordova-plugin-nativestorage#128]
In IOS devices, everytime when app starts, i am not getting the value from nativeStorage but if not restarting the app the value persists in native storage, please check what is the issue

**Comment by alokrajiv** [comment]
Can you be more specific with your issue. I didn’t quite understand.

Possibly add a code sample to showcase whatbyou are trying to do.

**Comment by sachinsemlety** [comment]
Hello @alokrajiv,
Actually, the scenario is, i am having login page, and i want to store the user credentials like username and password, so i am storing the user credentials in native storage plugin by setting, 

Code:

    this.nativeStorage.setItem('user_credentials', {user:'user',password:'123'})
      .then(
        () => console.log('Stored item!'),
        error => console.error('Error storing item', error)
      );
  }

after this, i am fetching the value by using,

  this.userCredentials = this.nativeStorage.getItem(key);          // here i  am getting the values from nativestorage plugin.

but if i close the app and again open the app at that time i am not getting any values from nativeStorage Plugin by using this,  this.userCredentials = this.nativeStorage.getItem(key); 

This only happens in ios devices like iphone 5,6 but it is working properly in android devices.
