### ISSUE TITLE
retrieving data from another app

### ISSUE THREAD

**Issue by azzuresky** [TheCocoaProject/cordova-plugin-nativestorage#143]
Hi would like to know if it is possible to get stored data from another app?
for example app-A store a data, then app-B retrieves it..

**Comment by GillesC** [comment]
Yes, see this link: https://stackoverflow.com/questions/39159754/how-get-data-from-cordova-plugin-nativestorage-in-android-java/39269620#39269620 and the F.A.Q. of the plugin https://github.com/TheCocoaProject/cordova-plugin-nativestorage#FAQ
