### ISSUE TITLE
MFP v8.o Push Rest Service Implementation sample java project or adapter

### ISSUE THREAD

**Issue by elavankarthik84** [TheCocoaProject/cordova-plugin-nativestorage#152]
Dear Team,
We are struggling to implement if use sdk based push service registration as per business needs so that we would request IBM team, if possible to share sample java based or adapter based PUSH rest API integration hands on code. it will really help us. below senario  we required ,

1 . how to register the notification user id with device based
2. how to send the notification with particular user id and device 

if above senario available sample hands, it will really help us. please do the needful.

**Comment by GillesC** [comment]
This is not related to the project.
