### ISSUE TITLE
NativeStorage.clear()?

### ISSUE THREAD

**Issue by zwacky** [TheCocoaProject/cordova-plugin-nativestorage#26]
hey there
i think a `window.NativeStorage.clear()` would make sense to have. what do you think?
cheers

**Comment by GillesC** [comment]
This is certainly possible. I will implement it when I've the time. Thanks for the good idea!

**Comment by GillesC** [comment]
Added `clear()` function (with callback's) with commit 8250903b87de76af037745bb8680ac3b25e16d7f.
Version has been updated tot v2.0.2 and after one last test, it will be published to NPM.

**Comment by GillesC** [comment]
Published on NPM: cordova-plugin-nativestorage@2.0.2
