### ISSUE TITLE
Uncaught ReferenceError: NativeStorage is not defined, http://localhost:8100/lib/ionic/js/ioni c.bundle.js, Line: 17946

### ISSUE THREAD

**Issue by tranjustin** [TheCocoaProject/cordova-plugin-nativestorage#30]
I have tried the script in the body   
<script type="text/javascript">   
    angular.element(document).ready(function () {
      if (window.cordova) {
        console.log("Running in Cordova, will bootstrap AngularJS once 'deviceready' event fires.");
        document.addEventListener('deviceready', function () {
          console.log("Deviceready event has fired, bootstrapping AngularJS.");
          angular.bootstrap(document.querySelector('body'), ['starter']);
        }, false);
      } else {
        console.log("Running in browser, bootstrapping AngularJS now.");
        angular.bootstrap(document.body, ['starter']);
      }
  }); </script>

it is working for Android but IOS i am getting that Uncaught ReferenceError: NativeStorage is not defined.  I am using xcode 7.3.1 and cordova 6.3.0.

**Comment by GillesC** [comment]
Are you sure the plugin is correctly installed for iOS? Please retry to install the plugin again (by removing and adding it). If your using Ionic 2 please check the [official Ionic Native docs](http://ionicframework.com/docs/v2/native/native-storage/).

**Comment by tranjustin** [comment]
I was able to get it working.  I am running into another issue.  I am trying to use this plugin to do persistent login.  However, the storage gets clear when the app is closed.

Justin Tran
Salt River Project
Software Engineer
Phone: 602-236-2131
Cell: 602-602-614-1799
Email: Justin.tran@srpnet.com<mailto:Justin.tran@srpnet.com>


From: Gilles Callebaut
Reply-To: TheCocoaProject/cordova-plugin-nativestorage
Date: Tuesday, August 2, 2016 at 9:45 PM
To: TheCocoaProject/cordova-plugin-nativestorage
Cc: jttran, Author
Subject: Re: [TheCocoaProject/cordova-plugin-nativestorage] Uncaught ReferenceError: NativeStorage is not defined, http://localhost:8100/lib/ionic/js/ioni c.bundle.js, Line: 17946 (#30)

***SRP EXTERNAL WARNING: PROCEED WITH CAUTION. WHEN IN DOUBT, REPORT IT!***
________________________________

Are you sure the plugin is correctly installed for iOS? Please retry to install the plugin again (by removing and adding it). If your using Ionic 2 please check the official Ionic Native docs<https://urldefense.proofpoint.com/v2/url?u=http-3A__ionicframework.com_docs_v2_native_native-2Dstorage_&d=CwMFaQ&c=akfg7FU5kpSpmm2ZSGIDmg&r=nVqS0RlVX30vkYmdV83xzLwshgnwTA1tdqLhzmddqfc&m=LROzFA51auW6ImPO7Rgss_W4wdTkD81mWjn4pF39_gQ&s=gsbzh9fwcpF-04_QkNv3qheL61A_xTxsFsJP5OGaCHY&e=>.

**Comment by GillesC** [comment]
@tranjustin are you sure the fault lies with the plugin?

- Are you storing the values correctly?

- Are you retrieving the values correctly (by using the same reference string AND the same method of storing, e.g. getItem only works when storing the value by means of setItem, getInt only with setInt,...) ?

**Comment by alokrajiv** [comment]
@tranjustin  technically the storage shouldn't be cleared. Are you seeing any error on the console?

**Comment by tranjustin** [comment]
I don’t believe it is the plugin.  I got it working on the browser but not on the devices or emulators.  To answer you Gilles, I am sure that I am storing and retrieving correctly from a browser perspective but don’t know what I might missed on the devices.

Justin Tran
Salt River Project
Software Engineer
Phone: 602-236-2131
Cell: 602-602-614-1799
Email: Justin.tran@srpnet.com<mailto:Justin.tran@srpnet.com>


From: Gilles Callebaut
Reply-To: TheCocoaProject/cordova-plugin-nativestorage
Date: Wednesday, August 3, 2016 at 2:27 PM
To: TheCocoaProject/cordova-plugin-nativestorage
Cc: jttran, Mention
Subject: Re: [TheCocoaProject/cordova-plugin-nativestorage] Uncaught ReferenceError: NativeStorage is not defined, http://localhost:8100/lib/ionic/js/ioni c.bundle.js, Line: 17946 (#30)

***SRP EXTERNAL WARNING: PROCEED WITH CAUTION. WHEN IN DOUBT, REPORT IT!***
________________________________

@tranjustin<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tranjustin&d=CwMFaQ&c=akfg7FU5kpSpmm2ZSGIDmg&r=nVqS0RlVX30vkYmdV83xzLwshgnwTA1tdqLhzmddqfc&m=CAXb5wFys-y38r8N-m-OWPJ1O1FbPEyhAJGbwYuCj8E&s=5p6T9kRthaBPbkVBEXV5St95oAeCBCqZCs1VzMd9KDI&e=> are you sure the fault lies with the plugin?

  *   Are you storing the values correctly?

  *   Are you retrieving the values correctly (by using the same reference string AND the same method of storing, e.g. getItem only works when storing the value by means of setItem, getInt only with setInt,...) ?

**Comment by alokrajiv** [comment]
@tranjustin  by browser, do you mean the `browser platform`?

**Comment by GillesC** [comment]
Can you please show us the code which should store and retrieve the values? And please do explain how you build, on the devices/browser? 

And another 'question' can you please explain in this thread how you've solved the '`Uncaught referenceError`' for future cases? :)

**Comment by tranjustin** [comment]
function loadUserCredentials() {
    return $q(function(resolve,reject){
        $log.log("load credential");
        var storedToken = $cordovaNativeStorage.getItem(LOCAL_TOKEN_KEY).then(function(value){
          $log.log("success load");
          $log.log(value);
        }, function(error){
          $log.log("error load");
          $log.log(error.message);
        });
        var authorizationStatus = storedToken.$$state;
        if (storedToken && authorizationStatus.status == 1) {
          var authorizationData = authorizationStatus.value;
          useCredentials(authorizationData);
          $log.log(authorizationData);
          resolve(authorizationData);
        }
        reject();
      });
    }

  function storeUserCredentials(authenticationData, keepmelogin) {
    var defer = $q.defer();
    if(!keepmelogin){
      authenticationData.refresh_token = "";
    }
    authenticationData.keepmelogin = keepmelogin;
    $cordovaNativeStorage.setItem(LOCAL_TOKEN_KEY, authenticationData).then(function(value){
      $log.log("success store");
      $log.log(value.name);
    }, function(error){
      $log.log("error store");
      $log.log(error.exception);
    });;
    useCredentials(authenticationData);
  }

Those two methods are in service that I call on $scope.$on('$ionicView.enter', function (){..}).  When I deployed using Xcode I see this message “Resetting plugins due to page load”. Unfortunately, I didn’t see any error.  I see the error string I logged but I don’t see the properties of the actual error I got back.  I have tried error.exception and error.message.  Do you know the properties inside the error that returns back?
[cid:FC409250-3A41-4311-B524-3FA1B68D3A95]

Justin Tran
Salt River Project
Software Engineer
Phone: 602-236-2131
Cell: 602-602-614-1799
Email: Justin.tran@srpnet.com<mailto:Justin.tran@srpnet.com>


From: Gilles Callebaut
Reply-To: TheCocoaProject/cordova-plugin-nativestorage
Date: Wednesday, August 3, 2016 at 2:34 PM
To: TheCocoaProject/cordova-plugin-nativestorage
Cc: jttran, Mention
Subject: Re: [TheCocoaProject/cordova-plugin-nativestorage] Uncaught ReferenceError: NativeStorage is not defined, http://localhost:8100/lib/ionic/js/ioni c.bundle.js, Line: 17946 (#30)

***SRP EXTERNAL WARNING: PROCEED WITH CAUTION. WHEN IN DOUBT, REPORT IT!***
________________________________

Can you please show us the code which should store and retrieve the values? And please do explain how you build, on the devices/browser?

And another 'question' can you please explain in this thread how you've solved the 'Uncaught referenceError' for future cases? :)

**Comment by tranjustin** [comment]
I forgot to mention I solved the "Uncaught referenceError” by upgrading ngcordova and this is the script I put in the index.html
  <script type="text/javascript">
    angular.element(document).ready(function () {
      if (window.cordova) {
        console.log("Running in Cordova, will bootstrap AngularJS once 'deviceready' event fires.");
        document.addEventListener('deviceready', function () {
          console.log("Deviceready event has fired, bootstrapping AngularJS.");
          angular.bootstrap(document.body, ['starter']);
        }, false);
      } else {
        console.log("Running in browser, bootstrapping AngularJS now.");
        angular.bootstrap(document.body, ['starter']);
      }
  }); </script>


Justin Tran
Salt River Project
Software Engineer
Phone: 602-236-2131
Cell: 602-602-614-1799
Email: Justin.tran@srpnet.com<mailto:Justin.tran@srpnet.com>


From: Gilles Callebaut
Reply-To: TheCocoaProject/cordova-plugin-nativestorage
Date: Wednesday, August 3, 2016 at 2:34 PM
To: TheCocoaProject/cordova-plugin-nativestorage
Cc: jttran, Mention
Subject: Re: [TheCocoaProject/cordova-plugin-nativestorage] Uncaught ReferenceError: NativeStorage is not defined, http://localhost:8100/lib/ionic/js/ioni c.bundle.js, Line: 17946 (#30)

***SRP EXTERNAL WARNING: PROCEED WITH CAUTION. WHEN IN DOUBT, REPORT IT!***
________________________________

Can you please show us the code which should store and retrieve the values? And please do explain how you build, on the devices/browser?

And another 'question' can you please explain in this thread how you've solved the 'Uncaught referenceError' for future cases? :)

**Comment by tranjustin** [comment]
Hey guys, by any chance you have run into this issue?  Whenever I shut the app down, the storage gets wiped out.  I thought this was being store in the keychain or keystore not localstorage.

Justin Tran
Salt River Project
Software Engineer
Phone: 602-236-2131
Cell: 602-602-614-1799
Email: Justin.tran@srpnet.com

**Comment by tranjustin** [comment]
Fix by using 

  <script type="text/javascript">
    angular.element(document).ready(function () {
      if (window.cordova) {
        console.log("Running in Cordova, will bootstrap AngularJS once 'deviceready' event fires.");
        document.addEventListener('deviceready', function () {
          console.log("Deviceready event has fired, bootstrapping AngularJS.");
          angular.bootstrap(document.body, ['starter']);
        }, false);
      } else {
        console.log("Running in browser, bootstrapping AngularJS now.");
        angular.bootstrap(document.body, ['starter']);
      }
  }); </script>
