### ISSUE TITLE
Is data persistent between app updates?

### ISSUE THREAD

**Issue by PierBover** [TheCocoaProject/cordova-plugin-nativestorage#32]

**Comment by PierBover** [comment]
So according to the wiki the plugin uses `SharedPreferences` for Android and `NSUserDefaults` for iOS, so yes the data should persist until the user deletes the Cordova app.

**Comment by alokrajiv** [comment]
@GillesC I think this a good question to be included in F.A.Q Thankyou @PierBover

**Comment by GillesC** [comment]
@alokrajiv Indeed, I will open a F.A.Q. section and put all (including these received by mail) the recieved questions there. @PierBover thank you for the question, this will also be beneficial to other users.
