### ISSUE TITLE
What types of data can be stored?

### ISSUE THREAD

**Issue by PierBover** [TheCocoaProject/cordova-plugin-nativestorage#33]
Is it possible to store an arrays, booleans, or JS objects?

The docs don't make that very clear.

**Comment by PierBover** [comment]
I just found about the wiki...

https://github.com/TheCocoaProject/cordova-plugin-nativestorage/wiki

**Comment by GillesC** [comment]
In general, anything that can be stringified, can be stored when using `getItem` and `setItem`. You can also be more fine grained and store objects with type-specific methods, see [API prior to v2](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/wiki/Usage-API-(prior-to-v2.0.0)).

**Comment by GillesC** [comment]
README has been updated with more info over the data types ([link](https://github.com/TheCocoaProject/cordova-plugin-nativestorage#supported_data_types)). Commit 743e79e9ec0acc122ca0117cc2d0f83addf2de4c
