### ISSUE TITLE
Why Async ?

### ISSUE THREAD

**Issue by agarwalswapnil** [TheCocoaProject/cordova-plugin-nativestorage#34]
Thanks for writing this plugin.
For iOS, NSUserDefaults is synchronous.
Why are we using `$cordovaNativeStorage.getItem` and `$cordovaNativeStorage.setItem` with callback/promises ?
Won't it be synchronous ?

**Comment by GillesC** [comment]
Why asynchonrous:
- Cordova makes all native operations work asynchronously with callbacks. See [this ](http://agiliq.com/blog/2012/09/dissecting-phonegaps-architecture/) 'old' blog about Cordova's architecture. The storage mechanisms may be synchrounous but calling and retrieving data from the 'native side' are asynchrounous. 
- Values can be retrieved while other code is being executed
- Callbacks are the nature of Javascript

I hope this gives you an idea why async is used here :)

**Comment by agarwalswapnil** [comment]
Thanks. The library is very helpful.

**Comment by dractw** [comment]
> Why asynchonrous:
> 
> * Cordova makes all native operations work asynchronously with callbacks. See [this ](http://agiliq.com/blog/2012/09/dissecting-phonegaps-architecture/) 'old' blog about Cordova's architecture. The storage mechanisms may be synchrounous but calling and retrieving data from the 'native side' are asynchrounous.
> * Values can be retrieved while other code is being executed
> * Callbacks are the nature of Javascript
> 
> I hope this gives you an idea why async is used here :)

But in another hand, you can simply calling callback and also returning the value synchronously.
That's make sense, when you making some cross-platform app with the same core with sort of Storage Interface, which uses, in case of mobile - NativeStorage or localStorage in webapp.

**Comment by alokrajiv** [comment]
@dractw can you clarify the comment. I didn't quite get you. Sorry :)
