### ISSUE TITLE
inconsistent error on browser

### ISSUE THREAD

**Issue by PierBover** [TheCocoaProject/cordova-plugin-nativestorage#40]
When getting an error on the `browser` platform, the result is an integer (or maybe a string) instead of a `NativeStorageError`.

**Comment by GillesC** [comment]
You were indeed correct.  [This commit](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/commit/4dcb5565f5229fa1527e0c39ee1e472d9e518ff3) should fixed it.

**Comment by PierBover** [comment]
Wow you guys are fast!

**Comment by GillesC** [comment]
I'm training to become as fast as the Flash! ;)
