### ISSUE TITLE
Issue with plugin version

### ISSUE THREAD

**Issue by pitAlex** [TheCocoaProject/cordova-plugin-nativestorage#41]
Hi,
There is something strange happening with the plugin version. I use cordova-check-plugins which returns that the latest version of this plugin is 2.1.0. I also see this version being reported in the npm site however everytime I run cordova plugin add cordova-plugin-nativestorage and then cordova plugin list, the version of it is 2.0.2.

**Comment by GillesC** [comment]
Thanks, a version number in one of the files was indeed not updated. :)

**Comment by GillesC** [comment]
Please reinstall the plugin ([see reinstalling the dev version](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/blob/master/README.md#reinstallinginstalling-developer-version))
