### ISSUE TITLE
Can't set item while in NativeStorage callback

### ISSUE THREAD

**Issue by bromeostasis** [TheCocoaProject/cordova-plugin-nativestorage#42]
Please let me know if this is intended behavior, but I didn't see any docs. I want to get the result of an item, and then set different items based on that value. Here's the code I'm using:

``` js
NativeStorage.getItem("oldestNewPerk", function (oldNew) {
                serverapi.getRecentPerkInfo(oldNew).done(function (data) {
                    console.log("First id: " + data.first_id + " , count: " + data.count)
                    NativeStorage.setItem("oldestNewPerk", data.first_id, null, function (err) {
                        console.log(err);
                    })
// ... etc
```

 Every time I do this, I get this error from setting the item:

```
// xcode
{"code":5,"source":"JS","exception":{"line":284,"column":14,"sourceURL":"file:///private/var/mobile/Containers/Bundle/Application/7DFD3A58-04CB-4816-B996-A626C03100FF/DiscountMeIn.app/www/plugins/cordova-plugin-nativestorage/www/mainHandle.js"}}
```
```
// safari
TypeError: undefined is not a function (evaluating 'error(new NativeStorageError(NativeStorageError.JSON_ERROR, "JS", err))')
```

Happy to elaborate more if necessary, but I can't use this plugin without this being handled.

**Comment by GillesC** [comment]
Meaning of the error codes: https://github.com/TheCocoaProject/cordova-plugin-nativestorage#error-codes

This means the value that is retrieved is not in a JSON-format and could therefore not be parsed. So print out your `data.first_id`. because that value could not be converted to a JSON object. So you check the reason why `JSON.parse` throws an error.

**Comment by bromeostasis** [comment]
@GillesC thanks for the response! I did a bit more logging, and it seems that data.first_id is a number, which should be parseable. More logs:

``` js
[Log] First id: 62356 , count: 115 (console-via-logger.js, line 174)
[Log] Object (console-via-logger.js, line 174)
code: 5
exception: Error
column: 14
line: 284
message: "null is not a function (evaluating 'success(obj)')"
name: "TypeError"

// Did some logging from a breakpoint in the code:
> data.first_id
< 62356
> typeof(data.first_id)
< "number"
```

Again, let me know if this makes sense/what additional info I can provide!

**Comment by GillesC** [comment]
`message: "null is not a function (evaluating 'success(obj)')"` is because you haven't implemented a success-callback function. Try this. Maybe this will also solve the JSON fault.

So after addition of success-callback:
```js
NativeStorage.getItem("oldestNewPerk", function (oldNew) {
                serverapi.getRecentPerkInfo(oldNew).done(function (data) {
                    console.log("First id: " + data.first_id + " , count: " + data.count)
                    NativeStorage.setItem("oldestNewPerk", data.first_id, function(){}, function (err) {
                        console.log(err);
                    })
```

**Comment by GillesC** [comment]
I think I will be solved by the proposed method above, i.e. addition of success-callback function.
If you look at the code in the plugin you could see that there is a try catch around the parsing and calling of the success-callback. So an error occurs because of the success-callback but the code (plugin) things it is a JSON parse error.

Internal code:
```js
this.storageHandlerDelegate(function(data) {
    try {
      obj = JSON.parse(data);
      success(obj);
    } catch (err) {
      error(new NativeStorageError(NativeStorageError.JSON_ERROR, "JS", err));
    }
  }, function(code) {
    error(new NativeStorageError(code, "Native", ""));
  }, "NativeStorage", "setItem", [reference, objAsString]);
};
```

**Comment by bromeostasis** [comment]
@GillesC I've had to move on to some other work, but I'll try this out and report back. What you're saying makes sense and thanks for your help!

**Comment by GillesC** [comment]
@bromeostasis any progress?

**Comment by bromeostasis** [comment]
@GillesC oof, still haven't had time to try this out. If you'd like, you can close the issue and I'll reopen it if I encounter any problems on trying it out.

Thanks for your help!
