### ISSUE TITLE
when use nativestorage in ionic2, and compile for android,show " java.lang.NoClassDefFoundError: NativeStorage",put the NativeStorage.java to a package fix it.

### ISSUE THREAD

**Issue by hangtoo** [TheCocoaProject/cordova-plugin-nativestorage#43]
10-20 14:55:55.890  31013-31013/com W/System.err﹕ Caused by: java.lang.NoClassDefFoundError: NativeStorage
10-20 14:55:55.890  31013-31013/com W/System.err﹕ ... 18 more
10-20 14:55:55.890  31013-31013/com W/System.err﹕ Caused by: java.lang.ClassNotFoundException: NativeStorage
10-20 14:55:55.890  31013-31013/com W/System.err﹕ at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
10-20 14:55:55.890  31013-31013/com W/System.err﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
10-20 14:55:55.890  31013-31013/com W/System.err﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
10-20 14:55:55.890  31013-31013/com W/System.err﹕ ... 18 more
10-20 14:55:55.890  31013-31013/com I/System.out﹕ Error adding plugin NativeStorage.
10-20 14:55:55.890  31013-31013/com W/System.err﹕ java.lang.NullPointerException
10-20 14:55:55.890  31013-31013/com W/System.err﹕ at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:172)
10-20 14:55:55.890  31013-31013/com W/System.err﹕ at org.apache.cordova.PluginManager.exec(PluginManager.java:123)
10-20 14:55:55.890  31013-31013/com W/System.err﹕ at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
10-20 14:55:55.890  31013-31013/com W/System.err﹕ at org.apache.cordova.CordovaBridge.promptOnJsPrompt(CordovaBridge.java:135)
10-20 14:55:55.890  31013-31013/com W/System.err﹕ at org.apache.cordova.engine.SystemWebChromeClient.onJsPrompt(SystemWebChromeClient.java:124)
10-20 14:55:55.890  31013-31013/com W/System.err﹕ at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:681)
10-20 14:55:55.900  31013-31013/com W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:99)
10-20 14:55:55.900  31013-31013/com W/System.err﹕ at android.os.Looper.loop(Looper.java:137)
10-20 14:55:55.900  31013-31013/com W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:4829)
10-20 14:55:55.900  31013-31013/com W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
10-20 14:55:55.900  31013-31013/com W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:511)
10-20 14:55:55.900  31013-31013/com W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
10-20 14:55:55.900  31013-31013/com W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
10-20 14:55:55.900  31013-31013/com W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ java.lang.ClassNotFoundException: NativeStorage
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at java.lang.Class.classForName(Native Method)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at java.lang.Class.forName(Class.java:217)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at java.lang.Class.forName(Class.java:172)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:490)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:170)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at org.apache.cordova.PluginManager.exec(PluginManager.java:123)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at org.apache.cordova.CordovaBridge.promptOnJsPrompt(CordovaBridge.java:135)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at org.apache.cordova.engine.SystemWebChromeClient.onJsPrompt(SystemWebChromeClient.java:124)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:681)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:99)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at android.os.Looper.loop(Looper.java:137)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:4829)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:511)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
10-20 14:55:55.910  31013-31013/com W/System.err﹕ Caused by: java.lang.NoClassDefFoundError: NativeStorage
10-20 14:55:55.920  31013-31013/com W/System.err﹕ ... 18 more

**Comment by GillesC** [comment]
Are you certain you have followed the correct procedures for installing the plugin in Ionic 2?
(http://ionicframework.com/docs/v2/native/)

**Comment by alokrajiv** [comment]
@hangtoo Any update?

**Comment by GillesC** [comment]
I'm closing this issue, because

1. I think the fault lies with the developer, not the plugin.
2. No more information is given by the issuer.
