### ISSUE TITLE
Possibility to use add browser environment support?

### ISSUE THREAD

**Issue by chrisbenseler** [TheCocoaProject/cordova-plugin-nativestorage#44]
I am currently using LocalStorage in an Ionic 2 app and was planning to use NativeStorage instead.
But the plugin does not work in the browser, so the development broke up using ionic serve and I guess it won't work too if I try to use my app as a "progressive web app".

Is it any plan to add support for the browser environment, maybe using as a layer above the browser localstorage? Does it make any sense?

[]s!

**Comment by GillesC** [comment]
The browser platform is supported. And it is indeed implementeren as a
layer on top of localstorage.

**Comment by danielmeng07** [comment]
@chrisbenseler It does work in browser. Make sure your code is not in callback format, but wrapped in 
```
  NativeStorage.getItem(...).then(function (value) {
    ...
  });
``` 
^ I missed this the first time around. 

According to the docs, you'll need `$scope.$apply()` if you're updating the scope.

**Comment by GillesC** [comment]
I'm closing this issue because the browser platform is supported see [the plain-JS docs](https://github.com/TheCocoaProject/cordova-plugin-nativestorage#supported_platforms) or see [the Ionic 2 ](http://ionicframework.com/docs/v2/native/nativestorage/ ) docs for the usage of the plugin.

**Comment by chrisbenseler** [comment]
Hi!

I tried using the example from the Ionic 2 docs (same link @GillesC provided) but the browser outputs these warning and error:

main.js:224 Native: tried calling NativeStorage.setItem, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
main.js:76063 Error storing item cordova_not_available

Am I missing something? Do I have to manually add the cordova.js file during my tests, while running the app in the webbrowser?

**Comment by GillesC** [comment]
@chrisbender I think the question is not related to a nativestorage bug. So it would be better to post your question on StackOverflow, with our tag and that from ionic 2. Provide a link to the SO post after you have posted your question to SO.

**Comment by chrisbenseler** [comment]
Thanks @GillesC 
Here is the link: http://stackoverflow.com/questions/40399008/ionic-2-use-nativestorage-in-the-browser

I'll try to find help in the Ionic 2 official forum, too!
