### ISSUE TITLE
$cordovaNativeStorage.clear is not a function

### ISSUE THREAD

**Issue by danielmeng07** [TheCocoaProject/cordova-plugin-nativestorage#45]
Error when calling `NativeStorage.clear`:

`Uncaught TypeError: $cordovaNativeStorage.clear is not a function`

```
    console.log($cordovaNativeStorage); // 3 methods - get, set, and remove. does not include clear. 
    var deferred = $q.defer();
    $cordovaNativeStorage.clear(function() { // throws 
      console.log('storage: cleared')
      deferred.resolve()
    }, function(err) {
      console.log(err);
    })
    return deferred.promise;
```

**Comment by GillesC** [comment]
This issue should be placed in the correct repo, i.e. [ngcordova-wrapper-nativestorage](https://github.com/TheCocoaProject/ngcordova-wrapper-nativestorage).

As the docs state, the `clear` function is not yet implemented. But I've merged a PR with a `clear` function so the current repo should now provide a proper  `clear` function. So please reinstall the wrapper. 
REMARK: The docs need to be updated to contain the `clear` functionality.

**Comment by danielmeng07** [comment]
Oops, didn't see that. My mistake.

**Comment by GillesC** [comment]
Hope the PR (pull request) solved your issue.
