### ISSUE TITLE
Uncaught TypeError: error is not a function

### ISSUE THREAD

**Issue by anwserman** [TheCocoaProject/cordova-plugin-nativestorage#48]
Hey,

Using Cordova on Windows 10/Browser.  Getting a "Uncaught TypeError: error is not a function" error at mainHandle.js:87.

The line throwing the error is:
 error("The type isn't supported or isn't been recognized");

I'm using Windows 10, Chrome 54, JQuery 3.1.1, Cordova 6.3.1, Android 5.2.2, Browser 4.1.0

Adding a generic 
`function error(e) { console.log(e); }`
doesn't work :/

**Comment by GillesC** [comment]
@anwserman Please provide the code you're using where the error is thrown. And maybe put some more information on the object your trying to save. Check for instance its type (via `typeof`).

**Comment by GillesC** [comment]
@anwserman I think you problem can be simular to [this issue](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/issues/42).

**Comment by Marvin256** [comment]
Hello

I'm having the same issue. Any workaround?

**Comment by GillesC** [comment]
Hello Marvin, have you seen my comment above yours? There I reference another issue, which I think is the same one as you're experiencing. And please provide more info. I'm unable to provide aid when I've nothing (or almost nothing) to work with.

**Comment by Marvin256** [comment]
Hey Gilles

Thanks for your answer. Yes I've seen the other issue but didn't found any answer to the problem.
Here's a part of the code generating the issue:

```
var app = {
    initialize: function () {
        this.bindEvents();
    },
    bindEvents: function () {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    onDeviceReady: function () {
        // On récupère le root de l'app sur PhoneGap
        var documentsDirectoryPath = decodeURIComponent(window.location.href);
        appRoot = documentsDirectoryPath.substring(0, documentsDirectoryPath.indexOf("index.html"));
        // On cache la barre de status
        StatusBar.hide();
        NativeStorage.getItem('role', this.getSuccess, this.getError);
        NativeStorage.getItem('airport', this.getSuccess, this.getError);
    },
    setSuccess: function (obj) {
        console.log(obj.name);
    },
    setError: function (error) {
        console.log(error.code);
        if (error.exception !== "") console.log(error.exception);
    },
    getSuccess: function (obj) {
        console.log(obj.name);
    },
    getError: function (error) {
        console.log(error.code);
        if (error.exception !== "") console.log(error.exception);
    },
    removeSuccess: function () {
        console.log("Removed");
    },
    removeError: function (error) {
        console.log(error.code);
        if (error.exception !== "") console.log(error.exception);
    }
};
```
As you can see it's almost a copy&paste from your exemple.
I didn't find any detailed documentation about your plugin so I'm little confuse with your code.
I'm compiling on Phongap Build.

Thank you a lot for your help.

Regards

**Comment by Marvin256** [comment]
mmm, I'm trying to understand your code but something looks weird to me. Can I use getItem & setItem with a string?
Is there public methods like getString & setString?
Do you have any documentation?

**Comment by GillesC** [comment]
@Marvin256 

Via the getItem you can store any object or data type that can be parsed via JSON. Hence, storing strings isn't a problem. If you are more familiar with compiled languages such as Java or C, look at the type-based storage API (< v2.0) [here](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/wiki/Usage-API-(prior-to-v2.0.0)). BTW as described in the README: more documentation can be found in the [wiki page](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/wiki).

When I look at your code I don't see any storing (setItem). So you should first store some values, prior to retrieving them.

**Comment by alokrajiv** [comment]
Made a commit 11cbc5a1c76539d34161a1d17728a92bca6f6f96 to silence this error.

Effectively it replaces error parameter at the JavaScript level with a dummy empty function if nothing was passed. Effectively making error parameter now option.

@GillesC  Could you update the docs if possible.
