### ISSUE TITLE
Put getItem inner another function

### ISSUE THREAD

**Issue by daniel82hien** [TheCocoaProject/cordova-plugin-nativestorage#49]
Hey,

I want to add it inner another function. Because I call getItem many time in my project.  Sample my code as (I use angularjs and phonegap):
$rootScope.getCookie = function (_name) {
    $cordovaNativeStorage.getItem(_name).then(function (value) {                        
       console.log('statement 1');
    });
}
var globals = $rootScope.getCookie('globals');
console.log('statement 2');
=> result on firebug's console: 'statement 2' appear before 'statement 1'.

I want 'statement 1' appear before 'statement 2'. Is it possible to do?

Please support me. Thanks.

**Comment by GillesC** [comment]
I think the question is not related to a nativestorage bug. So it would be better to post your question on StackOverflow, with our tag. Provide a link to the SO post after you have posted your question to SO.
