### ISSUE TITLE
Access stored values in Android

### ISSUE THREAD

**Issue by GillesC** [TheCocoaProject/cordova-plugin-nativestorage#53]
Variables can be accessed in Android by using the `getString` method provided by `SharedPreferences`. If NativeStorage API is used prior to v2.0 you need to use `getBoolean`, `getString`, `getDouble`,... corresponding to the variable type you have stored in JavaScript.

An Android snippet can be found here:
```java
private static final String PREFS_NAME = "NativeStorage";
private static final String KEY= "reference_to_var";
String value = getValue(Activity.this, KEY , null);
      

String getValue(Context context, String key, String defaultValue) {
   SharedPreferences settings = context.getSharedPreferences(PREFS_NAME, Activity.MODE_PRIVATE);
   return settings.getString(key, defaultValue);
}
```

It is imported that you use `"NativeStorage"` as the name of the preferences. 

Question on [StackOverflow](http://stackoverflow.com/questions/39159754/how-get-data-from-cordova-plugin-nativestorage-in-android-java/39269620#39269620).
Question on [Github](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/issues/52)

**Comment by Charles808** [comment]
Hi @GillesC  !

Could you please see my problem here ?
https://stackoverflow.com/questions/47073611/cordova-nativestorage-and-android

Your suggestion just don't work for me.
