### ISSUE TITLE
Get all keys for items in storage?

### ISSUE THREAD

**Issue by alexfoxy** [TheCocoaProject/cordova-plugin-nativestorage#56]
I'm storing a bunch of saved projects on an app I'm working on. When the user boots up I want to get all of their projects and list them. Previously I was saving the projects as JSON (stringified) to localStorage and pulling them out when the app booted up e.g:
```
for(var key in localStorage) {
    ...
}
```
I can't see a way to do something similar with NativeStorage. Would you suggest keeping an index in storage e.g. "project_ids" instead?

Thanks,
Alex

**Comment by GillesC** [comment]
If your always retrieving all the projects you could just store these projects in an array. Which can also be stored via NativeStorage.

**Comment by GillesC** [comment]
This feature is now implemented by @ydeshayes (through PR #61)

**Comment by alexfoxy** [comment]
Great, I did it the way you suggested any way but this will be useful in the future 👍
