### ISSUE TITLE
Android Entries Not Cleared

### ISSUE THREAD

**Issue by Maziar-Fotouhi** [TheCocoaProject/cordova-plugin-nativestorage#57]
I've noticed that recently the _NativeStorage_ entries are not being cleared after uninstalling the app. Looking at the [NativeStorage github](https://github.com/TheCocoaProject/cordova-plugin-nativestorage), it seems like android is using `Sharedpreferences`.

I googled [similar issues](http://stackoverflow.com/questions/35517239/sharedpreferences-are-not-being-cleared-when-i-uninstall) and it seems like, we have to set `android:allowBackup=false` in the _application_ tag of _AndroidManifest.xml_.

Currently, my _application_ tag looks like this:
` <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">`

**Comment by GillesC** [comment]
I don't think this is an issue, because we haven't stated in the docs that
the entries are not backed up. However, this could be added to the
documentation, that android can backup the data --by default.

**Comment by Maziar-Fotouhi** [comment]
@GillesC Thanks for the quick reply. The first FAQ entry in the docs actually implies something like that, when it says that "the data should be persistent until the app is deleted from the device.":

![image](https://cloud.githubusercontent.com/assets/12825530/21502405/1dd4af6c-cc15-11e6-8876-1c7975bf03a2.png)

**Comment by GillesC** [comment]
That sentence implies that persistence is ensured till uninstalling the app. It, however, does not say anything about maintaining persistence (or not) after uninstalling/reinstalling.

**Comment by GillesC** [comment]
But to avoid any further misunderstanding, I'll update the docs with your remark. Thank you for your contribution!

**Comment by Maziar-Fotouhi** [comment]
Thank you so much.
