### ISSUE TITLE
SyntaxError: Unexpected token when I call NativeStorage.getItem

### ISSUE THREAD

**Issue by JimmyChung1991** [TheCocoaProject/cordova-plugin-nativestorage#60]
Hi,
 private void cordovaPreference() {
//        Log.i("jimmy","url"+url);

        SharedPreferences mySharedPreferences = getSharedPreferences(PREFS_NAME, Activity.MODE_WORLD_READABLE);

        SharedPreferences.Editor editor = mySharedPreferences.edit();
        editor.putString("reference", "12342345fasdfaf");

        editor.commit();
    }
I store the reference in android 
Then I get it from  ionic side.
   NativeStorage.getItem("reference")
          .then(
              data=>console.log("nativestoragesuccess"+data),
              error=>console.error("nativestorageerror"+error.exception)
          );
The strange thing is that when I put "reference", "12342345" or the value is just num. It's ok But editor.putString("reference", "12342345fasdfaf") or any value contains a-z .It show SyntaxError: Unexpected token f .I don't get it

**Comment by GillesC** [comment]
So you've tried to save a value in Android via `putString` and retrieve it via `getItem` in JS.
I hope you've followed my 'instructions' [here](https://github.com/TheCocoaProject/cordova-plugin-nativestorage#faq)? 

What works (?):
- Saving (and retrieving) a string containing only numerical values

What doesn't work (?):
- Saving (and retrieving) a string containing only non-numerical values

To be of better help, please provide me with more logging information related to the error, e.g. where is the exception thrown.

**Comment by JimmyChung1991** [comment]
solved it Thanks,bro

**Comment by GillesC** [comment]
I'm glad it works now! Please consider explaining what the problem was, and how you solved it. This can come in handy for people with the same problems.
