### ISSUE TITLE
NativeStorageError code on browser is another NativeStorageError not an Integer as expected

### ISSUE THREAD

**Issue by alexfoxy** [TheCocoaProject/cordova-plugin-nativestorage#65]
Hey,

I upgraded from 2.0.2 to the latest version 2.2.1 and I'm encountering a problem in the browser. When I get an error (e.g. not found) the error looks like: 
<img width="263" alt="screen shot 2017-02-20 at 10 19 20" src="https://cloud.githubusercontent.com/assets/151772/23120884/15771bae-f756-11e6-81a9-785a408d2d32.png">

Previously the error code would be an Integer. From what I can see in the iOS version it also returns an Integer. I had a look through your commits and it seems your fix to issue #40 is the reason for this issue.

Is it a bug or am I missing something?

Thanks,
Alex

**Comment by alokrajiv** [comment]
Same as Issue #46. Closing here and tracking the issue there. 

Please feel free to comment if anyone thinks I am wrong. Always happy to reopen if necessary.
