### ISSUE TITLE
Nativestorage.getItem() error

### ISSUE THREAD

**Issue by theunreal** [TheCocoaProject/cordova-plugin-nativestorage#67]
When I'm trying to use `NativeStorage.getItem()` method, I get error code 2.
Why is that? It worked before.

**Comment by alokrajiv** [comment]
Error code 2 is `ITEM_NOT_FOUND`.

_Please consider posting your question on Stackoverflow. And add our own tag, [cordova-nativestorage](http://stackoverflow.com/tags/cordova-nativestorage) if your not sure its an issue of the plugin itself._
