### ISSUE TITLE
Storage is not cleared when calling .clear() and then reinstalling the app

### ISSUE THREAD

**Issue by NoNameProvided** [TheCocoaProject/cordova-plugin-nativestorage#71]
I know the persistent nature of NativeStorage and the fact that data persist between app reinstalls. But it seems `NativeStorage.clear()` doesn't work when we reinstall the app after it. (Tested on Android, don't know if iOS is affected as well.)

Lets say we save a token for auth: 
```js
NativeStorage.setItem('token', 'abc', console.log, console.error);
```

Then we restart the app and do 

```js
NativeStorage.getItem('token', console.log, console.error);
// Prints "abc"
NativeStorage.clear(console.log)
// Printis "OK"
```

After clearing the NativeStorage we reinstall the very same app and requesting the token will return the previously set value:

```js
NativeStorage.getItem('token', console.log, console.error);
// Prints "abc"
NativeStorage.clear(console.log)
// Printis "OK"
```

So clear doesn't seem to work when we reinstall the app. If we simply restart the app, the `token` won't be present, if we restart 10x times it's still won't be there, but if we reinstall the app again, the `token` will be there.

If we use `NatitveStorage.remove('token')` instead of `clear` everything works as expected.

**Comment by GillesC** [comment]
Hello,

Thank you for using my plugin.
I think this problem is related to the back-up mechanism used in Android, see [this](https://github.com/TheCocoaProject/cordova-plugin-nativestorage#faq).

I'll look further into this matter, and keep this issue open.

**Comment by GillesC** [comment]
For now I suggest using to set `android:allowBackup=false` in the application tag of the `AndroidManifest.xml`

**Comment by NoNameProvided** [comment]
I know about the `android:allowBackup=false` trick, but I have reported this because of the difference behaviour between using `clear` and the `remove` methods. It seems `remove` does trigger an immediate sync while calling `clear` does not.

A quick & ugly fix could be replacing the clear call in the JS side with a get keys + remove foreach call: 

```js
StorageHandle.prototype.clear = function (success, error) {
  if (inBrowser) {
    try {
      localStorage.clear();
      success();
    } catch (e) {
      error(e);
    }
  } else {
    StorageHandle.prototype.keys(function (keys) {
      var removeError;

      for(var i = 0; i<keys.length; i++) {
        StorageHandle.prototype.remove(keys[i], function (result) { }, function (error) { removeError = error; })
        if (removeError) {
          break;
        }
      }

      if(removeError) {
        error(removeError);
      }

    }, error)
  }
};
```

But this will need testing. (I just wrote the code here, haven't tested if it works.)

**Comment by alokrajiv** [comment]
So, It looks like we are doing exactly as the  [ Android API Docs](https://developer.android.com/reference/android/content/SharedPreferences.Editor.html#clear()) are saying.....
Let me try to replicate the issue.
I think running remove on all keys is okay, if we assume the number of keys will not be too much.

**Comment by alokrajiv** [comment]
@NoNameProvided  btw in your implementation, you are calling the `StorageHandle` async function inside the `for loop` right.

I guess we will need to use `async` or some counter to call a callback after all storagehandles exit because otherwise:
 ```
if(removeError) {
    error(removeError);
}
```
will run before the handles finish. and, the error will never be called.

**Comment by NoNameProvided** [comment]
Just checker I have figured out while was testing this in our app, seems haven't updated the answer here.

Thanks for the catch! ("catch" hehe 😄 )

**Comment by alokrajiv** [comment]
@NoNameProvided  just to confirm, you still face the issue with `clear()` right! Theoretically, Android API Docs says it should work as expected :|

**Comment by NoNameProvided** [comment]
We have finished that project, but I will take a look sometimes, and report back. Anyway thanks for looking into this.

**Comment by alokrajiv** [comment]
No worries, My bad...should have looked into it earlier. Didn't get time.

In the meantime, I will try to replicate on an emulator. Thanks for reporting!!

**Comment by NoNameProvided** [comment]
I have tried to reproduce the bug, with a newly created test app on the same test device (Nexus 5), but I could not. Magic. The only thing I can imagine, is one of the OS updates have fixed the issue. 

I guess we can close this.
