### ISSUE TITLE
Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by henkverschoor1994** [TheCocoaProject/cordova-plugin-nativestorage#72]
When I run this plugin in my Ionic 2 app, I got this error:
`plugins/cordova-plugin-nativestorage/www/LocalStorageHandle.js:37 Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

I am using this version:  `cordova-plugin-nativestorage 2.2.1 "NativeStorage"`

Can you fix this?

**Comment by GillesC** [comment]
Hello,

Please see issue #69 and PR #68.

**Comment by henkverschoor1994** [comment]
Thank you! But when will it come to the stable version?

**Comment by GillesC** [comment]
As soon as possible :)
