### ISSUE TITLE
Add support for NSUserDefaults for app groups

### ISSUE THREAD

**Issue by DavidStrausz** [TheCocoaProject/cordova-plugin-nativestorage#80]
Feature request:
I'd like to use this plugin to save user defaults for an app group and for later use in a today widget extension. Please let me know if this is possible somewhere in the near future or if I have to use [this](https://github.com/protonet/cordova-plugin-nsuserdefaults-for-app-groups) unmaintained plugin or a custom plugin.

Example from apple docs:
```
// Create and share access to an NSUserDefaults object
NSUserDefaults *mySharedDefaults = [[NSUserDefaults alloc] initWithSuiteName: @"com.example.domain.MyShareExtension"];
 
// Use the shared user defaults object to update the user's account
[mySharedDefaults setObject:theAccountName forKey:@"lastAccountName"];
```

**Comment by alokrajiv** [comment]
@GillesC anyway I can help?

**Comment by jasonz1987** [comment]
+1 need this
