### ISSUE TITLE
"Class not found" error when trying to use plugin

### ISSUE THREAD

**Issue by darshanrampatel** [TheCocoaProject/cordova-plugin-nativestorage#87]
I have installed the plugin into my Ionic v1 Cordova project.

I am trying to use the `setItem` function as below:

    $cordovaNativeStorage.setItem( "testRef", { testProp: true } ).then( function ( value ) {
    	console.log( value );
    }, function ( error ) {
    	console.error( error );
    } );

However, I get the below error:

![image](https://user-images.githubusercontent.com/14162899/28872948-4442cab6-7783-11e7-8848-8074f8dda177.png)

This also happens if I use the `NativeStorage.setItem( "testRef", { testProp: true }, this.setSuccess, this.setError );` format.

I'm not sure where "Class not found" is coming from or how to resolve this. Any ideas?

  [1]: https://github.com/TheCocoaProject/cordova-plugin-nativestorage

**Comment by GillesC** [comment]
Hello,
On which platform are you deploying your application?

**Comment by darshanrampatel** [comment]
@GillesC This is on Android 5.1.1

**Comment by darshanrampatel** [comment]
@GillesC, just to let you know, I upgraded my project to Android 6.2.3 and the issue has gone away.

**Comment by iursevla** [comment]
If someone else has this problem, try to run `ionic cordova build android` again. It solved the issue for me.
