### ISSUE TITLE
Missing setSecretItem & getSecretItem in ios library

### ISSUE THREAD

**Issue by sirg2003** [TheCocoaProject/cordova-plugin-nativestorage#95]
Hello. It seems there is missing functions in ios library files:
- getSecretItem
- setSecretItem
Any plans to implement?

**Comment by alokrajiv** [comment]
I'll let @GillesC be the judge of this feature's track.

But, my understanding is that as of now we haven't even documented it, and the fact that it is available as a hidden feature is just a matter of interest for advanced users.

You can track this feature process under Future Track section of the wiki.

Not very sure how many of our users really require this feature as well.

But, hey if you can make a PR -- that'd be great :)
